import type{AgentResponse,ApiEnvelope,ApiMeta,CreateSituationInput,CurrentSituation,IntegrationStatus,LayerCatalogItem,Observation,PriorityAreaResult,ProcedureStep,ReportDraft,ReportEvidenceSelection,SatelliteAsset,SimilarEvent,PhaseSelectionResult,SatelliteEvidenceSet,T3qIntegrationReadiness,T3qCqCoverage,T3qSearchPreview,T3qMockSearchScenarioDataset,T3qEventMaster,T3qPassage}from'../types/contracts';
import{selectFloodPhaseAssets as runSeedPhaseSelection,type SatelliteCandidate}from'../../../../server/domain/satellitePhaseSelection';
import{buildSeedResponseComparison,seedRecordEvidence}from'../domain/similarEventSeedFallback';
import type{AgentContextItem}from'../types/uiContext';
import type{DistrictReference,RiverReference,PlanReference}from'../types/planReference';
const API_BASE=import.meta.env.VITE_API_BASE_URL??'/api/v1';const FORCE_SEED=import.meta.env.VITE_USE_SEED_DIRECTLY==='true';
async function parseJson<T>(r:Response):Promise<T>{if(!r.ok)throw new Error(`HTTP ${r.status}: ${r.statusText}`);return r.json() as Promise<T>;}async function seed<T>(f:string):Promise<T>{return parseJson<T>(await fetch(`/seed/${f}`,{cache:'no-store'}));}async function apiEnvelope<T>(p:string,i?:RequestInit):Promise<ApiEnvelope<T>>{const e=await parseJson<ApiEnvelope<T>>(await fetch(`${API_BASE}${p}`,i));if(e.errors.length)throw new Error(e.errors.join(', '));return e;}async function apiData<T>(p:string,i?:RequestInit):Promise<T>{return (await apiEnvelope<T>(p,i)).data;}async function withFallback<T>(a:()=>Promise<T>,f:()=>Promise<T>):Promise<T>{if(FORCE_SEED)return f();try{return await a();}catch{return f();}}
export const loadSituations=():Promise<CurrentSituation[]>=>withFallback(()=>apiData('/scenarios'),async()=>(await seed<{situations:CurrentSituation[]}>('current_situations_seed.json')).situations);
export const createSituation=async(input:CreateSituationInput):Promise<CurrentSituation>=>{if(FORCE_SEED)return{situation_id:`SIT-LOCAL-${crypto.randomUUID()}`,admin_code:input.admin_code,admin_name:null,reference_time:input.reference_time??new Date().toISOString(),mode:input.mode??'scenario',hazards:input.hazards,user_input:input.user_input,observations:(input.observations??[]).map(o=>({...o,value_status:o.value_status??'scenario',data_status:o.data_status??'scenario',official_data:false})),data_quality:{mode:'seed_local',value_status:'scenario',official_data:false},warnings:['Seed 모드에서 로컬 생성된 Scenario 상황이며 서버 검증을 거치지 않았습니다.']};return apiData('/situations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});};
export const loadPriorityAreas=(s:CurrentSituation):Promise<PriorityAreaResult|null>=>withFallback(()=>apiData('/priority-areas/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({situation:s})}),async()=>{const p=await seed<{results:PriorityAreaResult[]}>('priority_areas_seed.json');return p.results.find(i=>i.situation_id===s.situation_id)??p.results.find(i=>i.situation_id.includes(s.admin_code))??null;});
export const loadSimilarEvents=(s:CurrentSituation):Promise<SimilarEvent[]>=>withFallback(()=>apiData('/similar-events/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({situation:s,top_k:5})}),async()=>{const p=await seed<{records:Array<Record<string,unknown>>}>('damage_recovery_events_seed.json');return p.records.filter(i=>i.admin_code===s.admin_code).map((r,index)=>{const evidence=seedRecordEvidence(r);const evidenceIds=evidence.map(e=>e.evidence_id);const referenceScore=80-index*5;return{event_id:String(r.event_id),record_id:String(r.record_id),admin_code:String(r.admin_code),admin_name:String(r.admin_name),event_name:String(r.event_name),occurred_from:String(r.occurred_from),occurred_to:typeof r.occurred_to==='string'?r.occurred_to:null,hazards:Array.isArray(r.hazards)?r.hazards.map(String):[],similarity_score:referenceScore,similarity_reasons:['Seed Fallback 참고 점수(요소별 실산정 유사도 아님)','동일 지자체 Seed 과거사례','재난유형 연관'],spatial_relation:'동일 지자체',similarity:{profile_id:'SEED-FALLBACK',profile_version:'1.3',event_similarity_score:referenceScore,retrieval_relevance_score:null,available_weight:65,comparison_coverage:65,confidence_status:'LIMITED',graph_similarity_score:null,graph_similarity_status:'NOT_AVAILABLE',factors:[]},response_comparison:buildSeedResponseComparison(s,r,evidenceIds),conditions:(r.conditions??{}) as Record<string,unknown>,damage:(r.damage??{}) as Record<string,unknown>,response:Array.isArray(r.response)?r.response as Array<Record<string,unknown>>:[],recovery:Array.isArray(r.recovery)?r.recovery as Array<Record<string,unknown>>:[],evidence,data_status:'mock',official_data:false,is_prediction:false,display_badges:Array.isArray(r.display_badges)?r.display_badges.map(String):[]} satisfies SimilarEvent;});});
export const loadProcedures=(c:string):Promise<ProcedureStep[]>=>withFallback(()=>apiData(`/procedures?admin_code=${encodeURIComponent(c)}`),async()=>{const p=await seed<{procedures:Array<ProcedureStep&{target_admin_codes?:string[]}>}>('response_procedures_seed.json');return p.procedures.filter(i=>i.target_admin_codes?.includes(c));});
export const loadSatelliteAssets=(c:string):Promise<SatelliteAsset[]>=>withFallback(()=>apiData(`/satellite-assets?admin_code=${encodeURIComponent(c)}`),async()=>{const p=await seed<{assets:SatelliteAsset[]}>('satellite_assets_seed.json');return p.assets.filter(i=>i.admin_code===c||i.shared_demo===true);});
export const loadLayers=():Promise<LayerCatalogItem[]>=>withFallback(()=>apiData('/map/layers'),async()=>(await seed<{layers:LayerCatalogItem[]}>('layer_catalog_seed.json')).layers);
export const loadIntegrationStatus=():Promise<IntegrationStatus[]>=>withFallback(()=>apiData('/integrations/status'),async()=>[]);
export const loadT3qReadiness=():Promise<{readiness:T3qIntegrationReadiness;summary:Record<string,number>}>=>(withFallback(()=>apiData('/t3q/readiness'),async()=>{const readiness=await seed<T3qIntegrationReadiness>('t3q_integration_readiness_seed.json');const summary=readiness.dimensions.reduce<Record<string,number>>((acc,row)=>{acc[row.state]=(acc[row.state]??0)+1;return acc;},{});return{readiness,summary};}));
export const loadT3qCqCoverage=(adminCode?:string):Promise<T3qCqCoverage>=>(withFallback(()=>apiData(`/t3q/cq-coverage${adminCode?`?admin_code=${encodeURIComponent(adminCode)}`:''}`),async()=>seed<T3qCqCoverage>('t3q_cq_coverage_seed.json')));

export const loadObservations=async(s:CurrentSituation):Promise<{observations:Observation[];meta:ApiMeta;warnings:string[]}>=>{if(FORCE_SEED)return{observations:s.observations,meta:{request_id:crypto.randomUUID(),provider:'seed_local',data_status:'scenario',fallback_used:true,generated_at:new Date().toISOString()},warnings:['Seed 모드: 상황에 저장된 사용자 입력·Scenario 관측값을 그대로 표시합니다.']};const e=await apiEnvelope<Observation[]>('/observations/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({admin_code:s.admin_code,reference_time:s.reference_time})});return{observations:e.data,meta:e.meta,warnings:e.warnings};};
/** 현재 조건 줄. `server/routes/v1/reports/drafts.ts`(29행)의 형식을 그대로 맞춘 Seed 전용 미러링이다.
 *  Seed 초안 원문은 산문("호우경보 시나리오")이라 지표 표로 렌더되지 않아 실서버 경로와 화면이 달라진다. */
const conditionLines=(s:CurrentSituation):string[]=>s.observations.map((item)=>`${item.name??item.type}: ${String(item.value)}${item.unit??''} (${item.value_status??'scenario'})`);
export const loadReport=(s:CurrentSituation,selectedEvidence?:ReportEvidenceSelection):Promise<ReportDraft|null>=>withFallback(()=>apiData('/reports/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({situation:s,selected_evidence:selectedEvidence})}),async()=>{const p=await seed<{reports:ReportDraft[]}>('report_draft_seed.json');const draft=p.reports.find(i=>i.situation_id===s.situation_id)??p.reports[0]??null;if(!draft)return null;return s.observations.length?{...draft,sections:{...draft.sections,current_conditions:conditionLines(s)}}:draft;});
export const sendAgentMessage=async(s:CurrentSituation,m:string,context:AgentContextItem[]=[]):Promise<AgentResponse>=>{
 if(FORCE_SEED){
  const[priority,similarEvents,procedures]=await Promise.all([loadPriorityAreas(s),loadSimilarEvents(s),loadProcedures(s.admin_code)]);
  const districtIds=context.filter(i=>i.kind==='district').map(i=>i.id);
  const eventIds=context.filter(i=>i.kind==='similar_event').map(i=>i.id);
  const areas=priority?.areas??[];
  // 선택 컨텍스트가 있으면 해당 대상을 앞으로 올려 질의와 함께 해석한 결과로 제시한다.
  const orderedAreas=districtIds.length?[...areas].sort((a,b)=>Number(districtIds.includes(b.spatial_object_id))-Number(districtIds.includes(a.spatial_object_id))):areas;
  const orderedEvents=eventIds.length?[...similarEvents].sort((a,b)=>Number(eventIds.includes(b.event_id))-Number(eventIds.includes(a.event_id))):similarEvents;
  const labels=context.map(i=>i.label).join(', ');
  const answer=context.length
   ?`선택한 대상(${labels})을 질의와 함께 해석했습니다. "${m}" — Seed 기반 우선 확인지역·유사사례·대응절차 참고정보를 표시합니다.`
   :`Seed 모드 Mock 응답입니다. "${m}" 질의에 대해 서버 Agent 로직 없이 Seed 기반 우선 확인지역·유사사례·대응절차 참고정보를 표시합니다.`;
  const mapActions=districtIds[0]?[{action:'highlight' as const,target_layer:'L-RISK',target_id:districtIds[0]}]:[];
  return{message_id:crypto.randomUUID(),answer,priority_areas:orderedAreas,similar_events:orderedEvents,procedures,map_actions:mapActions,evidence:[],warnings:['Seed 모드 Mock 응답이며 서버 Agent 로직을 거치지 않았습니다.'],limitations:['Scenario/Mock Seed 자료 기반이며 공식 위험도·피해예측·자동 조치결정이 아닙니다.'],operator_confirmation_required:true};
 }
 return apiData('/agent/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({situation:s,message:m,context})});
};
// 자연재해저감 종합계획·하천기본계획 판독 산출물. 정적 참고자료이므로 API 라우트 없이 public/seed 에서 직접 읽는다.
export const loadPlanReference=async(adminCode?:string|null):Promise<PlanReference>=>{
 const[districtSeed,riverSeed]=await Promise.all([seed<{districts:DistrictReference[]}>('districts.json'),seed<{rivers:RiverReference[]}>('rivers.json')]);
 const districts=adminCode?districtSeed.districts.filter(i=>i.admin_code===adminCode):districtSeed.districts;
 const rivers=adminCode?riverSeed.rivers.filter(i=>i.admin_code===adminCode):riverSeed.rivers;
 return{districts,rivers};
};
export function saveSituationView(s:CurrentSituation|null,selected:string|null){if(!s)return;const v={view_id:crypto.randomUUID(),saved_at:new Date().toISOString(),situation:s,selectedFeatureId:selected};localStorage.setItem(`une-disaster-view:${v.view_id}`,JSON.stringify(v));return v.view_id;}

export function loadReportEvidenceSelection(situationId:string):ReportEvidenceSelection{const raw=localStorage.getItem(`une-disaster-report-evidence:${situationId}`);if(raw){try{return JSON.parse(raw) as ReportEvidenceSelection;}catch{}}return{similar_event_ids:[],include_flood_trace:false,updated_at:new Date().toISOString()};}
export function saveReportEvidenceSelection(situationId:string,value:ReportEvidenceSelection){localStorage.setItem(`une-disaster-report-evidence:${situationId}`,JSON.stringify(value));}

export const selectFloodPhaseAssets=async(event:{event_id:string;event_start_at:string;event_end_at:string}):Promise<{event:typeof event;results:PhaseSelectionResult[]}>=>{if(FORCE_SEED){const p=await seed<{assets:SatelliteAsset[]}>('satellite_assets_seed.json');const candidates=p.assets.filter(i=>i.event_id===event.event_id) as unknown as SatelliteCandidate[];return{event,results:runSeedPhaseSelection(event,candidates)};}return apiData('/satellite-assets/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event})});};

export const loadSatelliteEvidenceSets=():Promise<SatelliteEvidenceSet[]>=>withFallback(()=>apiData('/satellite-evidence-sets'),async()=>{const p=await seed<{sets:SatelliteEvidenceSet[]}>('satellite_evidence_sets_seed.json');return p.sets;});

export const searchT3qMock=async(request:{query:string;admin_code?:string|null;taxonomy_codes?:string[];schema_types?:string[];top_k?:number}):Promise<T3qSearchPreview>=>{if(FORCE_SEED){const req={query:request.query,admin_code:request.admin_code??null,taxonomy_codes:request.taxonomy_codes??[],schema_types:request.schema_types??[],top_k:request.top_k??5};const[eventSeed,passageSeed]=await Promise.all([seed<{events:T3qEventMaster[]}>('t3q_mock_event_master_seed.json'),seed<{passages:T3qPassage[]}>('t3q_mock_passages_seed.json')]);const structural=passageSeed.passages.filter(row=>(!req.admin_code||row.admin_code===req.admin_code)&&(!req.taxonomy_codes.length||req.taxonomy_codes.some(code=>row.taxonomy_codes.includes(code)))&&(!req.schema_types.length||req.schema_types.includes(row.schema_type)));const q=req.query.trim().toLowerCase();const lexical=q?structural.filter(row=>`${row.title??''} ${row.content??''}`.toLowerCase().includes(q)):structural;const passages=lexical.length?lexical:structural;const eventIds=new Set(passages.map(row=>row.ref_disaster_event_id).filter(Boolean));let events=eventSeed.events.filter(row=>(!req.admin_code||row.region_code_5===req.admin_code)&&(!req.taxonomy_codes.length||req.taxonomy_codes.some(code=>row.taxonomy_codes.includes(code))));if(eventIds.size)events=events.filter(row=>eventIds.has(row.event_id));const warnings=['Seed Fallback 결과이며 T3Q 실데이터가 아닙니다.','현재 단계는 T3Q 외부 기술연계 없이 UNE Mock/Seed 계약으로만 동작합니다.'];if(q&&!lexical.length)warnings.push('질의어 직접일치 결과가 없어 행정구역·T코드·SchemaType 구조필터 결과를 사용했습니다.');if(!events.length&&!passages.length)warnings.push('조건에 맞는 Seed 데이터가 없습니다. 데이터 미확보 상태를 정상 결과로 처리합니다.');return{request:req,mode:'mock_contract',events:events.slice(0,req.top_k),passages:passages.slice(0,req.top_k),warnings};}return apiData('/t3q/search-preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taxonomy_codes:[],schema_types:[],top_k:5,...request})});};
export const loadT3qMockScenarios=():Promise<T3qMockSearchScenarioDataset>=>withFallback(()=>apiData('/mock/scenarios'),async()=>seed<T3qMockSearchScenarioDataset>('t3q_mock_search_scenarios_seed.json'));
