"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.seed = void 0;
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const runtime = globalThis;
const readJson = (...segments) => JSON.parse((0, node_fs_1.readFileSync)((0, node_path_1.join)(runtime.process?.cwd?.() ?? '.', 'data', ...segments), 'utf-8'));
const currentSituations = readJson('seed', 'current_situations_seed.json');
const priorities = readJson('seed', 'priority_areas_seed.json');
const procedures = readJson('seed', 'response_procedures_seed.json');
const satellites = readJson('seed', 'satellite_assets_seed.json');
const reports = readJson('seed', 'report_draft_seed.json');
const damageRecovery = readJson('seed', 'damage_recovery_events_seed.json');
const layers = readJson('seed', 'layer_catalog_seed.json');
const publicApiCatalog = readJson('seed', 'public_api_catalog_seed.json');
const scenarioTimelines = readJson('seed', 'scenario_timelines_seed.json');
const criteria = readJson('reference', 'criteria.json');
const districts = readJson('reference', 'districts.json');
const rivers = readJson('reference', 'rivers.json');
const geo = readJson('reference', 'geo.json');
const floodTraces = readJson('seed', 'flood_traces_seed.json');
const satelliteEvidenceSets = readJson('seed', 'satellite_evidence_sets_seed.json');
const t3qAlignment = readJson('seed', 't3q_alignment_seed.json');
const t3qReadiness = readJson('seed', 't3q_integration_readiness_seed.json');
const t3qCqCoverage = readJson('seed', 't3q_cq_coverage_seed.json');
const t3qFieldContract = readJson('seed', 't3q_field_contract_seed.json');
const providerContracts = readJson('seed', 'provider_contracts_seed.json');
const similarityWeightProfiles = readJson('seed', 'similarity_weight_profiles_seed.json');
const providerConformanceCases = readJson('seed', 'provider_conformance_cases_seed.json');
const t3qMockEvents = readJson('seed', 't3q_mock_event_master_seed.json');
const t3qMockPassages = readJson('seed', 't3q_mock_passages_seed.json');
const t3qMockRelations = readJson('seed', 't3q_mock_ontology_relations_seed.json');
const t3qMockSearchScenarios = readJson('seed', 't3q_mock_search_scenarios_seed.json');
const mockContractCatalog = readJson('seed', 'mock_contract_catalog_seed.json');
const mockFloodRiskAreas = readJson('seed', 'mock_flood_risk_areas_seed.json');
const mockDangerousReservoirs = readJson('seed', 'mock_dangerous_reservoirs_seed.json');
const mockStormFloodImprovementDistricts = readJson('seed', 'mock_storm_flood_improvement_districts_seed.json');
exports.seed = { currentSituations, priorities, procedures, satellites, reports, damageRecovery, layers, publicApiCatalog, scenarioTimelines, criteria, districts, rivers, geo, floodTraces, satelliteEvidenceSets, t3qAlignment, t3qReadiness, t3qCqCoverage, t3qFieldContract, t3qMockEvents, t3qMockPassages, t3qMockRelations, t3qMockSearchScenarios, mockContractCatalog, mockFloodRiskAreas, mockDangerousReservoirs, mockStormFloodImprovementDistricts, providerContracts, similarityWeightProfiles, providerConformanceCases };
