"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.seed = void 0;
const current_situations_seed_json_1 = __importDefault(require("../data/seed/current_situations_seed.json"));
const priority_areas_seed_json_1 = __importDefault(require("../data/seed/priority_areas_seed.json"));
const response_procedures_seed_json_1 = __importDefault(require("../data/seed/response_procedures_seed.json"));
const satellite_assets_seed_json_1 = __importDefault(require("../data/seed/satellite_assets_seed.json"));
const report_draft_seed_json_1 = __importDefault(require("../data/seed/report_draft_seed.json"));
const damage_recovery_events_seed_json_1 = __importDefault(require("../data/seed/damage_recovery_events_seed.json"));
const layer_catalog_seed_json_1 = __importDefault(require("../data/seed/layer_catalog_seed.json"));
const public_api_catalog_seed_json_1 = __importDefault(require("../data/seed/public_api_catalog_seed.json"));
const scenario_timelines_seed_json_1 = __importDefault(require("../data/seed/scenario_timelines_seed.json"));
const criteria_json_1 = __importDefault(require("../data/reference/criteria.json"));
const districts_json_1 = __importDefault(require("../data/reference/districts.json"));
const rivers_json_1 = __importDefault(require("../data/reference/rivers.json"));
const geo_json_1 = __importDefault(require("../data/reference/geo.json"));
const flood_traces_seed_json_1 = __importDefault(require("../data/seed/flood_traces_seed.json"));
const flood_mask_metrics_seed_json_1 = __importDefault(require("../data/seed/flood_mask_metrics_seed.json"));
const satellite_evidence_sets_seed_json_1 = __importDefault(require("../data/seed/satellite_evidence_sets_seed.json"));
const t3q_alignment_seed_json_1 = __importDefault(require("../data/seed/t3q_alignment_seed.json"));
const t3q_integration_readiness_seed_json_1 = __importDefault(require("../data/seed/t3q_integration_readiness_seed.json"));
const t3q_cq_coverage_seed_json_1 = __importDefault(require("../data/seed/t3q_cq_coverage_seed.json"));
const t3q_field_contract_seed_json_1 = __importDefault(require("../data/seed/t3q_field_contract_seed.json"));
const provider_contracts_seed_json_1 = __importDefault(require("../data/seed/provider_contracts_seed.json"));
const similarity_weight_profiles_seed_json_1 = __importDefault(require("../data/seed/similarity_weight_profiles_seed.json"));
const provider_conformance_cases_seed_json_1 = __importDefault(require("../data/seed/provider_conformance_cases_seed.json"));
const t3q_mock_event_master_seed_json_1 = __importDefault(require("../data/seed/t3q_mock_event_master_seed.json"));
const t3q_mock_passages_seed_json_1 = __importDefault(require("../data/seed/t3q_mock_passages_seed.json"));
const t3q_mock_ontology_relations_seed_json_1 = __importDefault(require("../data/seed/t3q_mock_ontology_relations_seed.json"));
const t3q_mock_search_scenarios_seed_json_1 = __importDefault(require("../data/seed/t3q_mock_search_scenarios_seed.json"));
const mock_contract_catalog_seed_json_1 = __importDefault(require("../data/seed/mock_contract_catalog_seed.json"));
const mock_flood_risk_areas_seed_json_1 = __importDefault(require("../data/seed/mock_flood_risk_areas_seed.json"));
const mock_dangerous_reservoirs_seed_json_1 = __importDefault(require("../data/seed/mock_dangerous_reservoirs_seed.json"));
const mock_storm_flood_improvement_districts_seed_json_1 = __importDefault(require("../data/seed/mock_storm_flood_improvement_districts_seed.json"));
exports.seed = { currentSituations: current_situations_seed_json_1.default, priorities: priority_areas_seed_json_1.default, procedures: response_procedures_seed_json_1.default, satellites: satellite_assets_seed_json_1.default, reports: report_draft_seed_json_1.default, damageRecovery: damage_recovery_events_seed_json_1.default, layers: layer_catalog_seed_json_1.default, publicApiCatalog: public_api_catalog_seed_json_1.default, scenarioTimelines: scenario_timelines_seed_json_1.default, criteria: criteria_json_1.default, districts: districts_json_1.default, rivers: rivers_json_1.default, geo: geo_json_1.default, floodTraces: flood_traces_seed_json_1.default, floodMaskMetrics: flood_mask_metrics_seed_json_1.default, satelliteEvidenceSets: satellite_evidence_sets_seed_json_1.default, t3qAlignment: t3q_alignment_seed_json_1.default, t3qReadiness: t3q_integration_readiness_seed_json_1.default, t3qCqCoverage: t3q_cq_coverage_seed_json_1.default, t3qFieldContract: t3q_field_contract_seed_json_1.default, t3qMockEvents: t3q_mock_event_master_seed_json_1.default, t3qMockPassages: t3q_mock_passages_seed_json_1.default, t3qMockRelations: t3q_mock_ontology_relations_seed_json_1.default, t3qMockSearchScenarios: t3q_mock_search_scenarios_seed_json_1.default, mockContractCatalog: mock_contract_catalog_seed_json_1.default, mockFloodRiskAreas: mock_flood_risk_areas_seed_json_1.default, mockDangerousReservoirs: mock_dangerous_reservoirs_seed_json_1.default, mockStormFloodImprovementDistricts: mock_storm_flood_improvement_districts_seed_json_1.default, providerContracts: provider_contracts_seed_json_1.default, similarityWeightProfiles: similarity_weight_profiles_seed_json_1.default, providerConformanceCases: provider_conformance_cases_seed_json_1.default };
